### ISSUE TITLE
Change in URL

### ISSUE THREAD

**Issue by bmcguirk** [jokecamp/epl-fantasy-geek#2]
I updated the get.rb file to at least permit login: 

```ruby
page  = agent.get "https://fantasy.premierleague.com/"

ARGV.each do|a|
  puts "Argument: #{a}"
end

# Fill out the login form
form  = page.form_with :class => 'ism-form ism-form--login'
form['ismjs-username']    = ARGV[0]
form['ismjs-password']    = ARGV[1]
form.submit
```
This works, but the URL where the statistics are maintained has moved, as well, and I'm not familiar enough with Mechanize to retrieve them: https://fantasy.premierleague.com/a/statistics/

Looks like this version of the site stores all possible templates as scripts every time you load the page, then populates them if you click the right link. Seems inefficient to me, but, regardless, the `div = page.at '#ismJson'` tag no longer works, for sure.

Any thoughts on how to capture this data somehow? Love your app, just want to be able to use it this season.

Thanks!

**Comment by jokecamp** [comment]
I'll have to take a look if the data is available.

**Comment by jokecamp** [comment]
This file has the data https://fantasy.premierleague.com/drf/bootstrap-static

The format has been changed so will require a lot of parsing and code changes.

They even have new stats this year. For example:

```
        "influence": "474.4",
        "creativity": "28.0",
        "threat": "176.0",
```

**Comment by jokecamp** [comment]
OK. Fixed for 16-17. Player list and filters work now.

https://github.com/jokecamp/epl-fantasy-geek/commit/4245d32acdfb6eef36def9cda76e3af26ec58501

**Comment by bmcguirk** [comment]
@jokecamp Woohoo! Thanks!
